/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.station.admin.GUI;

import bus.station.admin.GUI.FORMS.ConexionPostgres;
import javax.swing.JOptionPane;

/**
 *
 * @author Rivel
 */
public class datos_terminal extends javax.swing.JFrame {

    /**
     * Creates new form datos_terminal
     */
String[] DATOS;
    public datos_terminal(String sql) {
        initComponents();
      
        ConexionPostgres c = new ConexionPostgres();
        c.Conectar();
        String[] consulta=c.consultaDatosTerminal(sql);
      DATOS=consulta;
        this.jLabel9.setText("TERMINAL #"+consulta[0]);
        this.jTextField1.setText(consulta[1]);
        this.jTextField2.setText(consulta[2]);
        this.jTextField3.setText(consulta[3]);
        this.jTextField4.setText(consulta[4]);
      
          this.setLocationRelativeTo(null);
    }

    private datos_terminal() {
         //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        volver_lista_Terminales = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        modificar_Terminal_Button = new javax.swing.JButton();
        ver_lista_Choferes = new javax.swing.JButton();
        ver_lista_Autobuses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("TERMINAL #?");

        volver_lista_Terminales.setText("Atras");
        volver_lista_Terminales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver_lista_TerminalesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("DIRECCION");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("CAPACIDAD DE AUTOBUSES");

        jLabel3.setText("TELEFONO");

        jLabel4.setText("CODIGO POSTAL");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        modificar_Terminal_Button.setText("MODIFICAR DATOS DE LA TERMINAL");
        modificar_Terminal_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_Terminal_ButtonActionPerformed(evt);
            }
        });

        ver_lista_Choferes.setText("VER LISTA DE CHOFERES");
        ver_lista_Choferes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_lista_ChoferesActionPerformed(evt);
            }
        });

        ver_lista_Autobuses.setText("VER LISTA DE AUTOBUSES");
        ver_lista_Autobuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_lista_AutobusesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ver_lista_Autobuses)
                        .addGap(28, 28, 28)
                        .addComponent(ver_lista_Choferes)
                        .addGap(296, 296, 296))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(modificar_Terminal_Button)
                        .addGap(90, 90, 90))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(volver_lista_Terminales))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(volver_lista_Terminales)
                .addGap(10, 10, 10)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(modificar_Terminal_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ver_lista_Choferes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ver_lista_Autobuses, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void volver_lista_TerminalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver_lista_TerminalesActionPerformed
        lista_terminales LT = new lista_terminales();
        LT.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_volver_lista_TerminalesActionPerformed

    private void ver_lista_AutobusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_lista_AutobusesActionPerformed
        lista_autobuses LA = new lista_autobuses("select * from autobus");
        LA.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ver_lista_AutobusesActionPerformed

    private void ver_lista_ChoferesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_lista_ChoferesActionPerformed
        
        lista_choferes LC = new lista_choferes("select * from chofer");
        LC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ver_lista_ChoferesActionPerformed

    private void modificar_Terminal_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_Terminal_ButtonActionPerformed
        // TODO add your handling code here:
         bus.station.admin.GUI.FORMS.ConexionPostgres c = new bus.station.admin.GUI.FORMS.ConexionPostgres();
        c.Conectar();
        if(!DATOS[1].equalsIgnoreCase(this.jTextField1.getText())||!DATOS[2].equalsIgnoreCase(this.jTextField2.getText())
           ||!DATOS[3].equalsIgnoreCase(this.jTextField3.getText())||!DATOS[4].equalsIgnoreCase(this.jTextField4.getText()))
        {
            
            String botones[]={"Si modificar","Cancelar"};
            int variable = JOptionPane.showOptionDialog (null, " ¿Seguro que quieres modificar los datos de la terminal?", "Cita", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null/*icono*/, botones, botones[0]);
            if(variable==0)
            c.modificarTerminal(Integer.parseInt(DATOS[0]),this.jTextField1.getText() , Integer.parseInt(this.jTextField2.getText()), Long.parseLong(this.jTextField3.getText()),Integer.parseInt(this.jTextField4.getText()));    
            else
                JOptionPane.showMessageDialog(null, "Sin modificaciones");
        }else
                JOptionPane.showMessageDialog(null, "No hay datos modificados");
                      
        
    }//GEN-LAST:event_modificar_Terminal_ButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datos_terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datos_terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datos_terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datos_terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datos_terminal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton modificar_Terminal_Button;
    private javax.swing.JButton ver_lista_Autobuses;
    private javax.swing.JButton ver_lista_Choferes;
    private javax.swing.JButton volver_lista_Terminales;
    // End of variables declaration//GEN-END:variables
}
